name: pytorch-and-tensorflow-demo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  
  # Core ML Frameworks
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - tensorflow>=2.13.0
  
  # Data Science Libraries
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  
  # Jupyter Environment
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipywidgets>=8.0.0
  - notebook>=6.5.0
  
  # Development Tools
  - pytest>=7.4.0
  - ruff>=0.4.0
  - black>=24.0.0
  
  # Additional dependencies via pip
  - pip:
    - plotly>=5.15.0
    - nltk>=3.8.0
    - spacy>=3.6.0
    - transformers>=4.30.0
    - tokenizers>=0.13.0
    - tqdm>=4.65.0
    - opencv-python>=4.8.0
    - graphviz>=0.20.0
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - pydantic>=2.0.0
    - tensorflow-datasets>=4.9.0
    - mypy>=1.5.0